// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AffixData { id: string, group: string, value: number, stats: Record<string, number>, tags: Array<string>, requirements: Array<string>, is_local: boolean, }