// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageBreakdown } from "./DamageBreakdown";
import type { EhpSeries } from "./EhpSeries";
import type { TraceEntry } from "./TraceEntry";

export interface CalculatorOutput { dps_theoretical: number, dps_effective: number, hit_damage: number, rate: number, crit_chance: number, crit_multiplier: number, hit_chance: number, ehp_series: EhpSeries, damage_breakdown: DamageBreakdown, debug_trace: Array<TraceEntry>, }