// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemData } from "./ItemData";
import type { MechanicDefinition } from "./MechanicDefinition";
import type { MechanicState } from "./MechanicState";
import type { PreviewSlot } from "./PreviewSlot";
import type { SkillData } from "./SkillData";
import type { TargetConfig } from "./TargetConfig";

export interface CalculatorInput { context_flags: Record<string, boolean>, context_values: Record<string, number>, target_config: TargetConfig, items: Array<ItemData>, active_skill: SkillData, support_skills: Array<SkillData>, global_overrides: Record<string, number>, preview_slot: PreviewSlot | null, mechanic_states: Array<MechanicState>, mechanic_definitions: Array<MechanicDefinition>, }