// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageWithHistory } from "./DamageWithHistory";
import type { MultiplierBreakdown } from "./MultiplierBreakdown";

export interface DamageBreakdown { by_type: Record<string, number>, base_damage: number, total_increased: number, total_more: number, after_conversion: Record<string, DamageWithHistory>, multipliers: MultiplierBreakdown, }