// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AffixData } from "./AffixData";
import type { SlotType } from "./SlotType";

export interface ItemData { id: string, base_type: string, slot: SlotType, is_two_handed: boolean, base_implicit_stats: Record<string, number>, implicit_stats: Record<string, number>, affixes: Array<AffixData>, tags: Array<string>, is_unique: boolean, is_corrupted: boolean, }