// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MechanicState { id: string, current_stacks: number, max_stacks: number, is_active: boolean, }