// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MechanicDefinition { id: string, display_name: string, category: string, tag_key: string, default_max_stacks: number, base_effect_per_stack: Record<string, number>, description: string, }