// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneSource } from "./ZoneSource";

export interface MultiplierBreakdown { base_damage_zone: number, increased_zone: number, more_zone: number, crit_zone: number, speed_zone: number, hit_zone: number, defense_zone: number, resistance_zone: number, vulnerability_zone: number, mechanics_zone: number, zone_sources: Record<string, Array<ZoneSource>>, }