// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemData } from "./ItemData";
import type { SlotType } from "./SlotType";

export interface PreviewSlot { slot_type: SlotType, item: ItemData, }