// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SkillLevelData { effectiveness: number, base_damage: Record<string, number>, mana_cost: number | null, base_time: number | null, extra_effects: Record<string, number>, stats: Record<string, number>, }