// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillLevelData } from "./SkillLevelData";
import type { SkillScalingRule } from "./SkillScalingRule";
import type { SkillType } from "./SkillType";

export interface SkillData { id: string, skill_type: SkillType, damage_type: string | null, is_attack: boolean, level: number, base_damage: Record<string, number>, base_time: number, cooldown: number | null, mana_cost: number, effectiveness: number, tags: Array<string>, stats: Record<string, number>, injected_tags: Array<string>, mana_multiplier: number, level_data: SkillLevelData | null, scaling_rules: Array<SkillScalingRule>, }