// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SkillScalingRule { level_start: number, level_end: number | null, multiplier_per_level: number, }