// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlotType = "weapon_main" | "weapon_off" | "helmet" | "chest" | "gloves" | "boots" | "amulet" | "ring_1" | "ring_2" | "belt" | "memory_1" | "memory_2" | "memory_3" | "memory_4" | "memory_5" | "memory_6";