// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TargetConfig { level: number, defense_constant: number, resistances: Record<string, number>, generic_dr: number, armor: number, evasion: number, }