// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TraceEntry { phase: string, description: string, values: Record<string, number>, matched_tags: Array<string>, }